blank_issues_enabled: false
contact_links:
  - name: Feature Request 💡
    url: https://github.com/jagnesh/react-native-splash-view/
    about: If you have a feature request, please create a new discussion on GitHub.
  
